export default class FriendshipRequestConstants {
  static get ACCEPT_INTENT() { return 'FRIENDSHIP_REQUEST_ACCEPT_INTENT'; }
  static get ACCEPT_RESOLVED() { return 'FRIENDSHIP_REQUEST_ACCEPT_RESOLVED'; }
  static get ACCEPT_FAILED() { return 'FRIENDSHIP_REQUEST_ACCEPT_FAILED'; }
  static get REJECT_INTENT() { return 'FRIENDSHIP_REQUEST_REJECT_INTENT'; }
  static get REJECT_RESOLVED() { return 'FRIENDSHIP_REQUEST_REJECT_RESOLVED'; }
  static get REJECT_FAILED() { return 'FRIENDSHIP_REQUEST_REJECT_FAILED'; }
  static get MARK_AS_READ_INTENT() { return 'FRIENDSHIP_REQUEST_MARK_AS_READ_INTENT'; }
  static get MARK_AS_READ_RESOLVED() { return 'FRIENDSHIP_REQUEST_MARK_AS_READ_RESOLVED'; }
  static get MARK_AS_READ_FAILED() { return 'FRIENDSHIP_REQUEST_MARK_AS_READ_FAILED'; }
  static get GETTING_NEW_REQUEST() { return 'FRIENDSHIP_REQUEST_GETTING_NEW_REQUEST'; }
  static get ERROR_NEW_REQUEST() { return 'FRIENDSHIP_REQUEST_ERROR_NEW_REQUEST'; }
  static get NEW_REQUEST_GOT() { return 'FRIENDSHIP_REQUEST_NEW_REQUEST_GOT'; }
}
