export default class GroupConstants {
  static get LOADING_GROUP() { return 'GROUP_LOADING_GROUP'; }
  static get GROUP_LOADED() { return 'GROUP_GROUP_LOADED'; }
  static get ERROR_LOADING_GROUP() { return 'GROUP_ERROR_LOADING_GROUP'; }
  static get EDIT_GROUP() { return 'GROUP_EDIT_GROUP'; }
  static get EDIT_SHOWN() { return 'GROUP_EDIT_SHOWN'; }
  static get CANCEL_DELETE_GROUP() { return 'GROUP_CANCEL_DELETE_GROUP'; }
  static get DELETE_GROUP() { return 'GROUP_DELETE_GROUP'; }
  static get DELETING_GROUP() { return 'GROUP_DELETING_GROUP'; }
  static get GROUP_DELETED() { return 'GROUP_GROUP_DELETED'; }
  static get ERROR_DELETING_GROUP() { return 'GROUP_ERROR_DELETING_GROUP'; }
  static get RESET() { return 'GROUP_RESET'; }
  static get EXIT_GROUP() { return 'GROUP_EXIT_GROUP'; }
  static get CANCEL_EXIT_GROUP() { return 'GROUP_CANCEL_EXIT_GROUP'; }
  static get EXITING_GROUP() { return 'GROUP_EXITING_GROUP'; }
  static get GROUP_EXITED() { return 'GROUP_GROUP_EXITED'; }
  static get ERROR_EXITING_GROUP() { return 'GROUP_ERROR_EXITING_GROUP'; }
  static get ADDING_PLAYERS() { return 'GROUP_ADDING_PLAYERS'; }
  static get PLAYERS_ADDED() { return 'GROUP_PLAYERS_ADDED'; }
  static get ERROR_ADDING_PLAYERS() { return 'GROUP_ERROR_ADDING_PLAYERS'; }
  static get RESET_ADD_PLAYERS() { return 'GROUP_RESET_ADD_PLAYERS'; }
  static get BACK() { return 'GROUP_BACK'; }
  static get REMOVE_PLAYER() { return 'GROUP_REMOVE_PLAYER'; }
  static get CANCEL_REMOVE_PLAYER() { return 'GROUP_CANCEL_REMOVE_PLAYER'; }
  static get MAKE_PLAYER_ADMIN() { return 'GROUP_MAKE_PLAYER_ADMIN'; }
  static get CANCEL_MAKE_PLAYER_ADMIN() { return 'GROUP_CANCEL_MAKE_PLAYER_ADMIN'; }
  static get REMOVING_PLAYER() { return 'GROUP_REMOVING_PLAYER'; }
  static get PLAYER_REMOVED() { return 'GROUP_PLAYER_REMOVED'; }
  static get ERROR_REMOVING_PLAYER() { return 'GROUP_ERROR_REMOVING_PLAYER'; }
  static get MAKING_PLAYER_ADMIN() { return 'GROUP_MAKING_PLAYER_ADMIN'; }
  static get PLAYER_MADE_ADMIN() { return 'GROUP_PLAYER_MADE_ADMIN'; }
  static get ERROR_MAKING_PLAYER_ADMIN() { return 'GROUP_ERROR_MAKING_PLAYER_ADMIN'; }
  static get RESET_REMOVE_PLAYER() { return 'GROUP_RESET_REMOVE_PLAYER'; }
  static get RESET_MAKE_PLAYER_ADMIN() { return 'GROUP_RESET_MAKE_PLAYER_ADMIN'; }
  static get NEW_MESSAGE_RECEIVED() { return 'GROUP_NEW_MESSAGE_RECEIVED'; }
  static get SENDING_MESSAGE() { return 'GROUP_SENDING_MESSAGE'; }
  static get MESSAGE_SENT() { return 'GROUP_MESSAGE_SENT'; }
  static get ERROR_SENDING_MESSAGE() { return 'GROUP_ERROR_SENDING_MESSAGE'; }
}