export default class HomeConstants {
  static get SHOW_HOME_MENU() { return 'SHOW_HOME_MENU'; }
  static get HIDE_HOME_MENU() { return 'HIDE_HOME_MENU'; }
  static get CREATE_MATCH() { return 'CREATE_MATCH'; }
  static get SHOW_MATCH_DETAIL() { return 'SHOW_MATCH_DETAIL'; }
  static get LOADING_MATCHES() { return 'LOADING_MATCHES'; }
  static get ERROR_LOADING_MATCHES() { return 'ERROR_LOADING_MATCHES'; }
  static get MATCHES_LOADED() { return 'MATCHES_LOADED'; }
  static get LOADING_FRIENDS() { return 'LOADING_FRIENDS'; }
  static get FRIENDS_LOADED() { return 'FRIENDS_LOADED'; }
  static get ERROR_LOADING_FRIENDS() { return 'ERROR_LOADING_FRIENDS'; }
  static get LOADING_GROUPS() { return 'LOADING_GROUPS'; }
  static get GROUPS_LOADED() { return 'GROUPS_LOADED'; }
  static get ERROR_LOADING_GROUPS() { return 'ERROR_LOADING_GROUPS'; }
  static get SHOW_FRIEND() { return 'SHOW_FRIEND'; }
  static get SHOW_GROUP() { return 'SHOW_GROUP'; }
  static get UPDATING_FRIENDS() { return 'UPDATING_FRIENDS'; }
  static get FRIENDS_UPDATED() { return 'FRIENDS_UPDATED'; }
  static get UPDATING_FRIENDS_FAILED() { return 'UPDATING_FRIENDS_FAILED'; }
  static get UPDATING_GROUPS() { return 'UPDATING_GROUPS'; }
  static get GROUPS_UPDATED() { return 'GROUPS_UPDATED'; }
  static get UPDATING_GROUPS_FAILED() { return 'UPDATING_GROUPS_FAILED'; }
  static get LOADING_FRIENDSHIP_REQUEST() { return 'LOADING_FRIENDSHIP_REQUEST'; }
  static get FRIENDSHIP_REQUEST_LOADED() { return 'FRIENDSHIP_REQUEST_LOADED'; }
  static get LOADING_FRIENDSHIP_REQUEST_FAILED() { return 'LOADING_FRIENDSHIP_REQUEST_FAILED'; }
  static get MARK_AS_READ_INTENT() { return 'MARK_AS_READ_INTENT'; }
  static get MARK_AS_READ_RESOLVED() { return 'MARK_AS_READ_RESOLVED'; }
  static get MARK_AS_READ_FAILED() { return 'MARK_AS_READ_FAILED'; }
  static get LOGOUT_INTENT() { return 'LOGOUT_INTENT'; }
  static get LOGOUT_RESOLVED() { return 'LOGOUT_RESOLVED'; }
  static get LOGOUT_FAILED() { return 'LOGOUT_FAILED'; }
}