export default class MatchInvitationConstants {
  static get ACCEPT_INTENT() { return 'MATCH_INVITATION_ACCEPT_INTENT'; }
  static get ACCEPT_RESOLVED() { return 'MATCH_INVITATION_ACCEPT_RESOLVED'; }
  static get ACCEPT_FAILED() { return 'MATCH_INVITATION_ACCEPT_FAILED'; }
  static get REJECT_INTENT() { return 'MATCH_INVITATION_REJECT_INTENT'; }
  static get REJECT_RESOLVED() { return 'MATCH_INVITATION_REJECT_RESOLVED'; }
  static get REJECT_FAILED() { return 'MATCH_INVITATION_REJECT_FAILED'; }
  static get MARK_AS_READ_INTENT() { return 'MATCH_INVITATION_MARK_AS_READ_INTENT'; }
  static get MARK_AS_READ_RESOLVED() { return 'MATCH_INVITATION_MARK_AS_READ_RESOLVED'; }
  static get MARK_AS_READ_FAILED() { return 'MATCH_INVITATION_MARK_AS_READ_FAILED'; }
}
