export default class MatchDetailConstants {
  static get MATCH_DETAIL_CONFIRM_INTENT() { return 'MATCH_DETAIL_CONFIRM_INTENT'; }
  static get MATCH_DETAIL_CONFIRM_RESOLVED() { return 'MATCH_DETAIL_CONFIRM_RESOLVED'; }
  static get MATCH_DETAIL_CONFIRM_REJECTED() { return 'MATCH_DETAIL_CONFIRM_REJECTED'; }
}
